/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  LocationImage as PrismaLocationImage,
  Location as PrismaLocation,
} from "@prisma/client";

export class LocationImageServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.LocationImageCountArgs, "select">
  ): Promise<number> {
    return this.prisma.locationImage.count(args);
  }

  async locationImages(
    args: Prisma.LocationImageFindManyArgs
  ): Promise<PrismaLocationImage[]> {
    return this.prisma.locationImage.findMany(args);
  }
  async locationImage(
    args: Prisma.LocationImageFindUniqueArgs
  ): Promise<PrismaLocationImage | null> {
    return this.prisma.locationImage.findUnique(args);
  }
  async createLocationImage(
    args: Prisma.LocationImageCreateArgs
  ): Promise<PrismaLocationImage> {
    return this.prisma.locationImage.create(args);
  }
  async updateLocationImage(
    args: Prisma.LocationImageUpdateArgs
  ): Promise<PrismaLocationImage> {
    return this.prisma.locationImage.update(args);
  }
  async deleteLocationImage(
    args: Prisma.LocationImageDeleteArgs
  ): Promise<PrismaLocationImage> {
    return this.prisma.locationImage.delete(args);
  }

  async getLocation(parentId: string): Promise<PrismaLocation | null> {
    return this.prisma.locationImage
      .findUnique({
        where: { id: parentId },
      })
      .location();
  }
}
